#!/bin/bash -l
echo "begin environment carry test"
FOOBAR="from test_rvm"
export FOOBAR
echo "begin rvm test..."
whoami
echo $PATH
printenv
export PATH=$PATH:/usr/local/rvm:/usr/local/rvm/bin
echo $PATH
which ruby
which rvm
ruby --version
rvm --version
rvm list
# rvm use 2.5.3 --default
rvm use 2.5.3 --default
rvm list
ruby --version
echo "fin rvm test!"
